version: "3.8"

services:

  mock-api:
    image: node:18
    working_dir: /app
    volumes:
      - ./db.json:/app/db.json
    command: sh -c "npm install -g json-server && json-server --watch db.json --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"

  api-tests:
    build: ./test-framework
    depends_on:
      - mock-api
    environment:
      - BASE_URL=http://mock-api:3000

  jmeter:
    image: justb4/jmeter
    depends_on:
      - mock-api
    volumes:
      - ./performance/jmeter:/tests
    command: -n -t /tests/test-plan.jmx